### ISSUE TITLE
Search by ending

### ISSUE THREAD

**Issue by zigomir** [localvoid/ndx#1]
For example if you have a `body` of `sit amet` and search with `amet` you'l get the results, but if you search with `met` only, you won't get anything. I was wondering if this isn't working by design or is this a bug?

Thanks!

**Comment by localvoid** [comment]
Hi,

Yes, it is by design. But you can use [N-gram tokenizer](https://www.npmjs.com/package/n-gram) instead of the default tokenizer and inverted index will contain [N-grams](https://en.wikipedia.org/wiki/N-gram).

**Comment by zigomir** [comment]
I see, will dig further. Thank you for direction & `ndx` library!
